# NumPy Playground

In [5]:
import sys
!{sys.executable} -m pip install numpy

import numpy as np

  Using cached numpy-1.19.4-cp39-cp39-macosx_10_9_x86_64.whl (15.4 MB)
You should consider upgrading via the '/usr/local/Cellar/jupyterlab/2.2.9_1/libexec/bin/python -m pip install --upgrade pip' command.


# Zeros, ones and ranges

In [6]:
#Array init: lenght 4 with zeros 
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
#Array init with 4 arrays of 6 elements with ones and data type int16
np.ones((4, 6), dtype=np.int16)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)

In [9]:
#Array init with 2 arrays of 4 elements (empty) and random values
np.empty((2, 4))

array([[0.00000000e+000, 3.11108050e+231, 2.24979605e-314,
        2.13800152e-314],
       [2.24978456e-314, 2.13810729e-314, 2.13808221e-314,
        5.56270714e-309]])

In [13]:
#Array init with values from 4 to 26 with an incremental step of 2
np.arange(4,26,2)

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [15]:
#Array init with 5 numbers from 0 to 10
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Reshape, Resize, Shuffle, Choice, Elementwise

In [24]:
#Array init with 10 elements [0,1,2 ....,9] 
a = np.arange(10)

#Reshape the original array into a new one with 2 sub arrays with 5 elements
b = a.reshape(2,5)
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [25]:
#Resize the array itsself
a.resize(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [29]:
#Array init with 6 elements
a = np.arange(6)
print(a)

#Randomly shuffle the array modifying itself
np.random.shuffle(a)
print(a)

[0 1 2 3 4 5]
[3 2 1 5 4 0]


In [37]:
#Randomly choose an element in the list
random_element = np.random.choice(["temperature_sensor_a","temperature_sensor_b", "temperature_sensor_c"])
print(random_element)

temperature_sensor_a


In [40]:
#Generate a matrix by selecting random elements in the list
random_matrix = np.random.choice([10.2121, 10.3121, 10.4132, 10.3213], (2,3))
print(random_matrix)

[[10.3121 10.3213 10.3121]
 [10.4132 10.3121 10.4132]]


In [42]:
# Elementwise operations
temperature_array = np.array([20, 21.5, 19, 20.5])
conditions = temperature_array <= 19
print(conditions)

[False False  True False]


In [47]:
#Square array elements
a = np.array([10,20,30,40,50])
b = np.arange(5)
print(a)
print(b)

#Square array elements
b_square = b ** 2
print(b_square)

[10 20 30 40 50]
[0 1 2 3 4]
[ 0  1  4  9 16]


In [48]:
#Difference between array values
result_array = a - b
print(result_array)

[10 19 28 37 46]


# Aggregate, Indexing, Slicing

In [51]:
#Aggregate by summing the values
a = np.arange(10).reshape(2,5)
print(a)
values_sum = a.sum()
print(values_sum)

[[0 1 2 3 4]
 [5 6 7 8 9]]
45


In [61]:
#Sum each available row
rows_sum = a.sum(axis=1)
print(rows_sum)


#Max for each column
print(a.max(axis=0))

#Normalize each column
norm_result = a / a.max(axis=0)
print(norm_result)

[10 35]
[4 9]
[[0.         0.16666667 0.28571429 0.375      0.44444444]
 [1.         1.         1.         1.         1.        ]]


In [53]:
#Select each row in the second column
result_array = a[:,1]
print(result_array)

[1 6]


In [64]:
#Select target value
b = np.array([[0, 1, 2, 3],
            [10, 11, 12, 13],
            [20, 21, 22, 23]])
print(b)
print(b[2,3])

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]]
23


In [65]:
#Select each row in the second column of b
print(b[:,1])

[ 1 11 21]


In [66]:
#Select the target range in b
print(b[1:3,0:2])

[[10 11]
 [20 21]]
